import Head from "next/head";

export default function Wallet() {
  return (
    <>
      <Head>
        <title>Orders Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="flexing">
          <h1>Wallet</h1>
        </div>
      </div>
    </>
  );
}
