export const orderListData = [
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    type: "admin",
    items: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 3,
        review: 253,
      },
      {
        name: "Italiano pizza with garlic",
        count: 2,
        price: 50,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    userName: "Eren Yeager",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    type: "customer",
    items: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Levi Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    status: "Delivered",
    items: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Armin Melaney",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    status: "New Order",
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Grisha Yeager",
    type: "customer",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    items: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Historia Reuss",
    location: "Corner Street 5th London",
    amount: 164.52,
    type: "customer",
    items: [
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
      {
        name: "Watermelon juice with ice",
        count: 5,
        price: 10,
        stars: 1,
        review: 453,
      },
    ],
    status: "Delivered",
  },
];

export const customerListData = [
  {
    id: "1",
    customerId: "C-004560",
    date: "27 March 2020, 12:42 AM",
    customerName: "Veronica",
    location: "Corner Street 5th, London",
    spent: 78,
    lastOrder: 35,
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    job: "Highspeed Studios",
    field: "UX Designer",
    creditCard: {
      money: 1204,
      cardNum: "2451 3243 2342 9799",
      exp: "02/21",
      owner: "Eren Yeager",
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: "2",
    customerId: "C-004561",
    date: "27 March 2020, 12:42 AM",
    customerName: "Rio Da Luca",
    location: "Corner Street 5th, London",
    spent: 78,
    lastOrder: 35,
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    job: "Highspeed Studios",
    field: "UX Designer",
    creditCard: {
      money: 9425,
      cardNum: "2451 3243 2342 9799",
      exp: "02/21",
      owner: "Grisha Yeager",
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: "3",
    customerId: "C-004562",
    date: "27 March 2020, 12:42 AM",
    customerName: "Fernando",
    location: "Corner Street 5th, London",
    spent: 78,
    lastOrder: 35,
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    job: "Highspeed Studios",
    field: "UX Designer",
    creditCard: {
      money: 1125,
      cardNum: "2451 3243 2342 9799",
      exp: "02/21",
      owner: "Historia Reuss",
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: "4",
    customerId: "C-004563",
    date: "27 March 2020, 12:42 AM",
    customerName: "Yenni Tan",
    location: "Corner Street 5th, London",
    spent: 78,
    lastOrder: 35,
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    job: "Highspeed Studios",
    field: "Backend Developer",
    creditCard: {
      money: 10025,
      cardNum: "2451 3243 2342 9799",
      exp: "02/21",
      owner: "Levi Ackerman",
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
  {
    id: "5",
    customerId: "C-004564",
    date: "27 March 2020, 12:42 AM",
    customerName: "Denny Chang",
    location: "Corner Street 5th, London",
    spent: 78,
    lastOrder: 35,
    email: "eren.yeager@mail.co.id",
    phone: "+012 345 6789",
    job: "Highspeed Studios",
    field: "Frontend Developer",
    creditCard: {
      money: 2300,
      cardNum: "2451 3243 2342 9799",
      exp: "02/21",
      owner: "Armin Melaney",
    },
    items: [
      {
        id: 1,
        foodName: "Chicken Caesar Salad",
        food: "SALAD",
        price: 72.5,
        person: 3,
        min: 20,
      },
      {
        id: 2,
        foodName: "Beef Wellington",
        food: "BEEF",
        price: 90.0,
        person: 4,
        min: 25,
      },
    ],
  },
];

export const foodData = [
  {
    id: "1",
    category: "Food",
    type: "Burger",
    price: 200,
    name: "Burger Jumbo Special With Spicy",
    ingredients:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    comment:
      "Pepperoni pitsasi (20 cm), qarsildoq kartoshka fri va ishtahaochar stripslar (3 ta) – shunchalar mazaliki, beixtiyor yana deb yuborasiz!",
  },
  {
    id: "2",
    category: "Food",
    price: 100,
    type: "Pizza",
    name: "Pizza la Piazza Special Nuggets",
    ingredients:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    comment:
      "Pepperoni pitsasi (20 cm), qarsildoq kartoshka fri va ishtahaochar stripslar (3 ta) – shunchalar mazaliki, beixtiyor yana deb yuborasiz!",
  },
  {
    id: "3",
    category: "Food",
    price: 400,
    type: "Noodle",
    name: "Spicy Mozarella with Barbeque",
    ingredients:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    comment:
      "Pepperoni pitsasi (20 cm), qarsildoq kartoshka fri va ishtahaochar stripslar (3 ta) – shunchalar mazaliki, beixtiyor yana deb yuborasiz!",
  },
  {
    id: "4",
    category: "Drink",
    type: "Sprite",
    price: 300,
    name: "Sprite Flavour with Avocado Juice",
    ingredients:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    comment:
      "Pepperoni pitsasi (20 cm), qarsildoq kartoshka fri va ishtahaochar stripslar (3 ta) – shunchalar mazaliki, beixtiyor yana deb yuborasiz!",
  },
  {
    id: "4",
    category: "Drink",
    type: "Sprite",
    price: 300,
    name: "Sprite Flavour with Avocado Juice",
    ingredients:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    nutritionInfo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    comment:
      "Pepperoni pitsasi (20 cm), qarsildoq kartoshka fri va ishtahaochar stripslar (3 ta) – shunchalar mazaliki, beixtiyor yana deb yuborasiz!",
  },
];
